// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gcmyplxuewxrhdnikpqg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdjbXlwbHh1ZXd4cmhkbmlrcHFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMTIwNDgsImV4cCI6MjA2ODU4ODA0OH0.Mk5dPGAX-0prGRb-SFbYhm7MkzDjX-GXWW8yX74ASag";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});